### ISSUE TITLE
connection() error occurred during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AtlasError) bad auth : Authentication failed. exit status 1

### ISSUE THREAD

**Issue by wg-d** [amTechie/to-do-app-go#3]
$ go run main.go
2022/05/18 15:50:49 connection() error occurred during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AtlasError) bad auth : Authentication failed.
exit status 1

**Comment by amTechie** [comment]
const connectionString = "mongodb+srv://alexleebizz:668416cjcjh@cluster0.ekwa6.mongodb.net/?retryWrites=true&w=majority"
